## YAML Template.
---

new:
  is_secure: on
  credentials: admin
  
create:
  is_secure: on
  credentials: admin
  
edit:
  is_secure: on
  credentials: admin
  
update:
  is_secure: on
  credentials: admin
  
delete:
  is_secure: on
  credentials: admin
  
download:
  is_secure: on
  
