INSERT INTO `biblioteca_2`.`provincia` (`nombre`) VALUES ('Chubut');
INSERT INTO `biblioteca_2`.`localidad` (`nombre`, `cod_postal`, `provincia_id_provincia`) VALUES ('Esquel', '9200', 1);

INSERT INTO `biblioteca_2`.`tipo_doc` (`nombre`) VALUES ('dni');

INSERT INTO `biblioteca_2`.`pfisica` (`nombre`, `apellido`, `tipo_doc_id_tipo_doc`, `documento`) VALUES ('gabriel', 'figueroa', 1, '123456');

INSERT INTO `biblioteca_2`.`usuario` (`id_usuario`, `usuario`, `password`, `admin`) VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 1);

INSERT INTO `biblioteca_2`.`contenido` (`numero_contenido`, `nombre`) VALUES (1, 'Generalidades');
INSERT INTO `biblioteca_2`.`subcontenido` (`nombre`, `numero_subcontenido`, `contenido_id_contenido`) VALUES ('informatica', 'abc', 1);



INSERT INTO `biblioteca_2`.`pjuridica` (`razon_social`) VALUES ('prestar libros');

INSERT INTO `biblioteca_2`.`biblioteca` (`nombre`, `pjuridica_id_pjuridica`) VALUES ('udc', 1);
INSERT INTO `biblioteca_2`.`carrera` (`nombre`) VALUES ('software');








INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Calculo de una variable', 'Cengage Learning', 'Stewart, James','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'El calculo', '', 'Leithold, Louis','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Enfermeria Medico Quirurgica', 'Elsevier Mosby', 'Swearingen, Pamela L.','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Diccionario Mosby pocket de medicina …', 'Elsevier', 'Elsevier','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Diagnostico Enfermero', 'Mosby Dayma libros', 'Gordon, Marjory','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Informacion Tecnology', 'Oxford', 'Demetriades Dinos','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Investigacion cualitativa en enfermeria', 'OMS', 'Doprado, Martha (y otros)','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Tecnica Dietoterapica', 'El Ateneo', 'Longo, Elsa y Navarro, Elizabeth','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Manual de etica y legislacion en enfermeria', 'Mosby ', 'Pastor Garcia, Luis y Leon Carrera, F.','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Vademecuon de medicamentos de uso en Arg.', 'Clyna', 'Editorial Clyna S.A','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Algebra 1', 'Magister eos', 'Rojo, Armando','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Comunicaciones y redes de computadores', 'Pearson Prentice', 'Stalling, William','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'The Merrian Webster Dictionary', 'Merrian Webster', 'Merrian Webster','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Diccionario Enciclopedico de enfermeria', 'Panamericana', 'Miller, Keane','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Diccionario de la lengua española T1', 'RAE', 'REAL ACADEMIA ESPAÑOLA','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Diccionario de la lengua española T2', 'RAE', 'REAL ACADEMIA ESPAÑOLA','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Diccionario de informatica telecomunicaciones y …', 'Diaz de Santos S.A', 'Leon, Mario','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Modelos de sicologia comunitaria para la …', 'OPS/OMS', 'Balcazar, Fabricio (y otros)','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Diagostico Enfermero', 'Elsevier ', 'Elsevier','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Aplicación del proceso enfermero', 'Elsevier', 'Lefevre, Rosalinda Alfaro','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Problemas musculo- esqueleticos', 'Masson', 'Masson','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Problemas metabolicos', 'Masson', 'Masson','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Proceso de enfermeria y diagnostico de enfermeria', 'Mc Graw - Hill', 'Iyer, Patricia  W. (y otros)','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Planificiacion estrategica de recursos humanos en …', 'OMS', 'Rovare, Mario R.','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Lo esencial en sistema nervioso y sentidos …', 'Mosby', 'Lasserson, Daniel (y otros)','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Lo esencial en aparato digestivo', 'Mosby', 'Cheshire, Elizabeth','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Manejo integral de urgencias', 'Panamericana', 'MalaGon Londoño, Gustavo ( y colabs)','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Sistemas operativos', 'Prentice Hall', 'Tanembaum, A y Woodhull, A','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Electronica digital: Logica ', 'Alfaomega', 'Acha, Santiago  (y otros)','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Diseño y evaluacion de arquitecturas de …', 'Pearson ', 'Beltran Pardo, M. y Guzman Sacristan, A.','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Electronica digital facil', 'Alfaomega', 'Ruiz Vasallo, francisco','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
INSERT INTO `biblioteca_2`.`material` (`id_material`, `archivo`, `titulo`, `editorial`, `autor`, `descripcion`, `fisico`, `subcontenido_id_subcontenido`, `biblioteca_id_biblioteca`, `carrera_id_carrera`) VALUES (NULL,'', 'Arquitectura de computadoras', 'Alfaomega', 'Quiroga, Patricia','', '1', '1', '1', '1');
