# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, "styles.css", "jquery-ui-1.10.4.custom.css", "jquery-ui-1.10.4.custom.min.css"]

  javascripts:    ["jquery-1.10.2.js", "main.js", "jquery.pajinate.js", "jquery-ui-1.10.4.custom.js", "tinymce/tinymce.min.js", "funciones.js"]

  has_layout:     true
  layout:         layout
