propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  carrera:
    _attributes: { phpName: Carrera, idMethod: native }
    id_carrera: { phpName: IdCarrera, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: false }
    material_id_material: { phpName: MaterialIdMaterial, type: INTEGER, required: true, foreignTable: material, foreignReference: id_material }
    _indexes: { fk_carrera_material1: [material_id_material] }
  contenido:
    _attributes: { phpName: Contenido, idMethod: native }
    id_contenido: { phpName: IdContenido, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    numero_contenido: { phpName: NumeroContenido, type: INTEGER, required: false, index: unique }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: false }
  librito:
    _attributes: { phpName: Librito, idMethod: native }
    id_librito: { phpName: IdLibrito, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    name: { phpName: Name, type: VARCHAR, size: '45', required: false }
    price: { phpName: Price, type: VARCHAR, size: '45', required: false }
  librito_pdf:
    _attributes: { phpName: LibritoPdf, idMethod: native }
    id_librito_pdf: { phpName: IdLibritoPdf, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    filename: { phpName: Filename, type: VARCHAR, size: '45', required: false }
    caption: { phpName: Caption, type: VARCHAR, size: '45', required: false }
    librito_id_librito: { phpName: LibritoIdLibrito, type: INTEGER, required: true, foreignTable: librito, foreignReference: id_librito }
    _indexes: { fk_librito_pdf_librito: [librito_id_librito] }
  libro:
    _attributes: { phpName: Libro, idMethod: native }
    idlibro: { phpName: Idlibro, type: INTEGER, primaryKey: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: false }
    archivo: { phpName: Archivo, type: BLOB, required: false }
  material:
    _attributes: { phpName: Material, idMethod: native }
    id_material: { phpName: IdMaterial, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    archivo: { phpName: Archivo, type: VARCHAR, size: '45', required: false }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: false }
    titulo: { phpName: Titulo, type: VARCHAR, size: '45', required: false }
    editorial: { phpName: Editorial, type: VARCHAR, size: '45', required: false }
    autor: { phpName: Autor, type: VARCHAR, size: '45', required: false }
    descripcion: { phpName: Descripcion, type: LONGVARCHAR, required: false }
    subcontenido_id_subcontenido: { phpName: SubcontenidoIdSubcontenido, type: INTEGER, required: true, foreignTable: subcontenido, foreignReference: id_subcontenido }
    _indexes: { fk_material_subcontenido1: [subcontenido_id_subcontenido] }
  subcontenido:
    _attributes: { phpName: Subcontenido, idMethod: native }
    id_subcontenido: { phpName: IdSubcontenido, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: false }
    numero_subcontenido: { phpName: NumeroSubcontenido, type: INTEGER, required: false, index: unique }
    contenido_id_contenido: { phpName: ContenidoIdContenido, type: INTEGER, required: true, foreignTable: contenido, foreignReference: id_contenido }
    _indexes: { fk_subcontenido_contenido1: [contenido_id_contenido] }
  usuario:
    _attributes: { phpName: Usuario, idMethod: native }
    idusuario: { phpName: Idusuario, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: false }
    password: { phpName: Password, type: VARCHAR, size: '45', required: false }
