propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  acceso_material:
    _attributes: { phpName: AccesoMaterial, idMethod: native }
    id_acceso_material: { phpName: IdAccesoMaterial, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    fecha_acceso: { phpName: FechaAcceso, type: TIMESTAMP, required: true, defaultExpr: CURRENT_TIMESTAMP }
    material_id_material: { phpName: MaterialIdMaterial, type: INTEGER, required: true, foreignTable: material, foreignReference: id_material, onDelete: CASCADE, onUpdate: CASCADE }
    usuario_id_usuario: { phpName: UsuarioIdUsuario, type: INTEGER, required: true, foreignTable: usuario, foreignReference: id_usuario }
    _indexes: { fk_acceso_material_material1: [material_id_material], fk_acceso_material_usuario1: [usuario_id_usuario] }
  anuncio:
    _attributes: { phpName: Anuncio, idMethod: native }
    id_anuncio: { phpName: IdAnuncio, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    titulo: { phpName: Titulo, type: VARCHAR, size: '45', required: false }
    informacion: { phpName: Informacion, type: CLOB, required: true }
    fecha_anuncio: { phpName: FechaAnuncio, type: TIMESTAMP, required: true, defaultExpr: CURRENT_TIMESTAMP }
    usuario_id_usuario: { phpName: UsuarioIdUsuario, type: INTEGER, required: true, foreignTable: usuario, foreignReference: id_usuario }
    _indexes: { fk_anuncio_usuario1: [usuario_id_usuario] }
  aporte:
    _attributes: { phpName: Aporte, idMethod: native }
    id_aporte: { phpName: IdAporte, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    archivo: { phpName: Archivo, type: CLOB, required: true }
    titulo: { phpName: Titulo, type: VARCHAR, size: '45', required: false }
    descripcion: { phpName: Descripcion, type: LONGVARCHAR, required: false }
    usuario_id_usuario: { phpName: UsuarioIdUsuario, type: INTEGER, required: true, foreignTable: usuario, foreignReference: id_usuario }
    _indexes: { fk_aporte_usuario1: [usuario_id_usuario] }
  biblioteca:
    _attributes: { phpName: Biblioteca, idMethod: native }
    id_biblioteca: { phpName: IdBiblioteca, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
    pjuridica_id_pjuridica: { phpName: PjuridicaIdPjuridica, type: INTEGER, required: true, foreignTable: pjuridica, foreignReference: id_pjuridica }
    _indexes: { fk_biblioteca_pjuridica1: [pjuridica_id_pjuridica] }
  carrera:
    _attributes: { phpName: Carrera, idMethod: native }
    id_carrera: { phpName: IdCarrera, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
  carrera_fisica:
    _attributes: { phpName: CarreraFisica, idMethod: native }
    id_carrera_fisica: { phpName: IdCarreraFisica, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    carrera_id_carrera: { phpName: CarreraIdCarrera, type: INTEGER, required: true, foreignTable: carrera, foreignReference: id_carrera, onDelete: CASCADE, onUpdate: CASCADE }
    pfisica_id_pfisica: { phpName: PfisicaIdPfisica, type: INTEGER, required: true, foreignTable: pfisica, foreignReference: id_pfisica }
    _indexes: { fk_carrera_fisica_carrera1: [carrera_id_carrera], fk_carrera_fisica_pfisica1: [pfisica_id_pfisica] }
  contenido:
    _attributes: { phpName: Contenido, idMethod: native }
    id_contenido: { phpName: IdContenido, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    numero_contenido: { phpName: NumeroContenido, type: VARCHAR, size: '45', required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
  domicilio:
    _attributes: { phpName: Domicilio, idMethod: native }
    id_domicilio: { phpName: IdDomicilio, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    barrio: { phpName: Barrio, type: VARCHAR, size: '45', required: false }
    calle: { phpName: Calle, type: VARCHAR, size: '45', required: true }
    altura: { phpName: Altura, type: VARCHAR, size: '45', required: true }
    cod_postal: { phpName: CodPostal, type: VARCHAR, size: '45', required: false }
    real: { phpName: Real, type: BOOLEAN, size: '1', required: false }
    localidad_id_localidad: { phpName: LocalidadIdLocalidad, type: INTEGER, required: true, foreignTable: localidad, foreignReference: id_localidad }
    pfisica_id_pfisica: { phpName: PfisicaIdPfisica, type: INTEGER, required: true, foreignTable: pfisica, foreignReference: id_pfisica }
    _indexes: { fk_domicilio_localidad1: [localidad_id_localidad], fk_domicilio_pfisica1: [pfisica_id_pfisica] }
  domicilio_j:
    _attributes: { phpName: DomicilioJ, idMethod: native }
    id_domicilio_j: { phpName: IdDomicilioJ, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    barrio: { phpName: Barrio, type: VARCHAR, size: '45', required: false }
    calle: { phpName: Calle, type: VARCHAR, size: '45', required: true }
    altura: { phpName: Altura, type: VARCHAR, size: '45', required: true }
    cod_postal: { phpName: CodPostal, type: VARCHAR, size: '45', required: false }
    real: { phpName: Real, type: BOOLEAN, size: '1', required: false }
    localidad_id_localidad: { phpName: LocalidadIdLocalidad, type: INTEGER, required: true, foreignTable: localidad, foreignReference: id_localidad }
    pjuridica_id_pjuridica: { phpName: PjuridicaIdPjuridica, type: INTEGER, required: true, foreignTable: pjuridica, foreignReference: id_pjuridica }
    _indexes: { fk_domicilio_localidad1: [localidad_id_localidad], fk_domicilio_j_pjuridica1: [pjuridica_id_pjuridica] }
  lista:
    _attributes: { phpName: Lista, idMethod: native }
    id_lista: { phpName: IdLista, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    informacion: { phpName: Informacion, type: LONGVARCHAR, required: false }
    material_id_material: { phpName: MaterialIdMaterial, type: INTEGER, required: true, foreignTable: material, foreignReference: id_material }
    usuario_id_usuario: { phpName: UsuarioIdUsuario, type: INTEGER, required: true, foreignTable: usuario, foreignReference: id_usuario }
    _indexes: { fk_lista_usuario1: [usuario_id_usuario], fk_lista_material1: [material_id_material] }
  localidad:
    _attributes: { phpName: Localidad, idMethod: native }
    id_localidad: { phpName: IdLocalidad, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
    cod_postal: { phpName: CodPostal, type: VARCHAR, size: '45', required: true }
    provincia_id_provincia: { phpName: ProvinciaIdProvincia, type: INTEGER, required: true, foreignTable: provincia, foreignReference: id_provincia }
    _indexes: { fk_localidad_provincia1: [provincia_id_provincia] }
  material:
    _attributes: { phpName: Material, idMethod: native }
    id_material: { phpName: IdMaterial, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    archivo: { phpName: Archivo, type: CLOB, required: false }
    titulo: { phpName: Titulo, type: VARCHAR, size: '45', required: true }
    editorial: { phpName: Editorial, type: VARCHAR, size: '45', required: false }
    autor: { phpName: Autor, type: VARCHAR, size: '45', required: false }
    descripcion: { phpName: Descripcion, type: LONGVARCHAR, required: false }
    fisico: { phpName: Fisico, type: BOOLEAN, size: '1', required: false }
    tema_id_tema: { phpName: TemaIdTema, type: INTEGER, required: true, foreignTable: tema, foreignReference: id_tema }
    biblioteca_id_biblioteca: { phpName: BibliotecaIdBiblioteca, type: INTEGER, required: true, foreignTable: biblioteca, foreignReference: id_biblioteca }
    _indexes: { fk_material_biblioteca1: [biblioteca_id_biblioteca], fk_material_tema1: [tema_id_tema] }
  material_aporte:
    _attributes: { phpName: MaterialAporte, idMethod: native }
    id_material_aporte: { phpName: IdMaterialAporte, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    material_id_material: { phpName: MaterialIdMaterial, type: INTEGER, required: true, foreignTable: material, foreignReference: id_material }
    aporte_id_aporte: { phpName: AporteIdAporte, type: INTEGER, required: true, foreignTable: aporte, foreignReference: id_aporte }
    _indexes: { fk_material_aporte_material1: [material_id_material], fk_material_aporte_aporte1: [aporte_id_aporte] }
  material_carrera:
    _attributes: { phpName: MaterialCarrera, idMethod: native }
    id_material_carrera: { phpName: IdMaterialCarrera, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    material_id_material: { phpName: MaterialIdMaterial, type: INTEGER, required: true, foreignTable: material, foreignReference: id_material }
    carrera_id_carrera: { phpName: CarreraIdCarrera, type: INTEGER, required: true, foreignTable: carrera, foreignReference: id_carrera }
    _indexes: { fk_material_carrera_material1: [material_id_material], fk_material_carrera_carrera1: [carrera_id_carrera] }
  pfisica:
    _attributes: { phpName: Pfisica, idMethod: native }
    id_pfisica: { phpName: IdPfisica, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
    apellido: { phpName: Apellido, type: VARCHAR, size: '45', required: true }
    varon: { phpName: Varon, type: BOOLEAN, size: '1', required: false }
    fecha_nac: { phpName: FechaNac, type: DATE, required: true }
    tipo_doc_id_tipo_doc: { phpName: TipoDocIdTipoDoc, type: INTEGER, required: true, foreignTable: tipo_doc, foreignReference: id_tipo_doc, onDelete: CASCADE, onUpdate: CASCADE }
    documento: { phpName: Documento, type: VARCHAR, size: '45', required: true }
    _indexes: { fk_pfisica_tipo_doc1: [tipo_doc_id_tipo_doc] }
  pjuridica:
    _attributes: { phpName: Pjuridica, idMethod: native }
    id_pjuridica: { phpName: IdPjuridica, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
    razon_social: { phpName: RazonSocial, type: VARCHAR, size: '45', required: true }
    cuit_cuil: { phpName: CuitCuil, type: VARCHAR, size: '45', required: true }
  provincia:
    _attributes: { phpName: Provincia, idMethod: native }
    id_provincia: { phpName: IdProvincia, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
  subcontenido:
    _attributes: { phpName: Subcontenido, idMethod: native }
    id_subcontenido: { phpName: IdSubcontenido, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
    numero_subcontenido: { phpName: NumeroSubcontenido, type: VARCHAR, size: '45', required: false }
    contenido_id_contenido: { phpName: ContenidoIdContenido, type: INTEGER, required: true, foreignTable: contenido, foreignReference: id_contenido, onDelete: CASCADE, onUpdate: CASCADE }
    _indexes: { fk_subcontenido_contenido1: [contenido_id_contenido] }
  tema:
    _attributes: { phpName: Tema, idMethod: native }
    id_tema: { phpName: IdTema, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
    numero_tema: { phpName: NumeroTema, type: VARCHAR, size: '45', required: false }
    subcontenido_id_subcontenido: { phpName: SubcontenidoIdSubcontenido, type: INTEGER, required: true, foreignTable: subcontenido, foreignReference: id_subcontenido }
    _indexes: { fk_tema_subcontenido1: [subcontenido_id_subcontenido] }
  tipo_doc:
    _attributes: { phpName: TipoDoc, idMethod: native }
    id_tipo_doc: { phpName: IdTipoDoc, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
  usuario:
    _attributes: { phpName: Usuario, idMethod: native }
    id_usuario: { phpName: IdUsuario, type: INTEGER, primaryKey: true, required: true, foreignTable: pfisica, foreignReference: id_pfisica, onDelete: CASCADE, onUpdate: CASCADE }
    valido: { phpName: Valido, type: BOOLEAN, size: '1', required: false }
    usuario: { phpName: Usuario, type: VARCHAR, size: '45', required: true, index: unique }
    password: { phpName: Password, type: VARCHAR, size: '45', required: true }
    admin: { phpName: Admin, type: BOOLEAN, size: '1', required: false }
    email: { phpName: Email, type: VARCHAR, size: '45', required: false }
