propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  
  tipo_doc:
    nombre: { primaryString: true }
  carrera:
    nombre: { primaryString: true }
  biblioteca:
    nombre: { primaryString: true }
  subcontenido:
    nombre: { primaryString: true }
  provincia:
    nombre: { primaryString: true }
  localidad:
    nombre: { primaryString: true }
    provincia_id_provincia: { primaryString: true }
  pjuridica:
    nombre: { primaryString: true }
  usuario:
    usuario: { primaryString: true }
  material:
    titulo: { primaryString: true }
  contenido:
    nombre: { primaryString: true }